application/json:
  examples:
    update-user-profile-payload:
      description: All elements are optional but one should be required
      value:
        {
          "firstName": "Joe",
          "lastName": "New",
          "middleName": "Doe",
          "dob": "1976-12-24"
        }
