body:
  application/json:
    examples:
      invalid-token-value:
        value:
          {
              "statusCode": 400,
              "message": "Password reset token is invalid or has expired",
              "errorDetails": []
          }

      empty-payload:
        value:
          {
            "statusCode": 400,
            "message": "\"password\" is required",
            "errorDetails": [
              {
                  "message": "\"password\" is required",
                  "path": [
                      "password"
                  ],
                  "type": "any.required",
                  "context": {
                      "label": "password",
                      "key": "password"
                  }
              }
            ]
          }

      short-password:
        value:
          {
            "statusCode": 400,
            "message": "\"password\" length must be at least 5 characters long",
            "errorDetails": [
              {
                "message": "\"password\" length must be at least 5 characters long",
                "path": [
                    "password"
                ],
                "type": "string.min",
                "context": {
                    "limit": 5,
                    "value": "12",
                    "label": "password",
                    "key": "password"
                }
              }
            ]
          }

      missing-token:
       value:
          {
              "statusCode": 400,
              "message": "\"token\" is required",
              "errorDetails": [
                  {
                      "message": "\"token\" is required",
                      "path": [
                          "token"
                      ],
                      "type": "any.required",
                      "context": {
                          "label": "token",
                          "key": "token"
                      }
                  }
              ]
          }

      password-not-matching:
        value:
          {
            "statusCode": 400,
            "message": "Password do not match",
            "errorDetails": [
                "12123123",
                "111111"
            ]
          }
