body:
  application/json:
    examples:
      user-profile:
        description: "User Profile"
        value:
          {
              "statusCode": 200,
              "data": {
                  "isConfirmed": false,
                  "confirmedAt": null,
                  "_id": "5fc6d83b8ba197fcea946157",
                  "firstName": "Joe",
                  "lastName": "New",
                  "middleName": "Doe",
                  "email": "joe.doe@demo5.com",
                  "dob": "Thu Dec 23 1976 18:00:00 GMT-0600 (hora estándar central)",
                  "createdAt": "2020-12-01T23:56:43.464Z",
                  "updatedAt": "2020-12-02T15:27:23.213Z"
              }
          }
