body:
  application/json:
    examples:
      account-activated:
        description: Confirms the account
        value:
          {
              "statusCode": 200,
              "data": "Activation complete"
          }
