body:
  application/json:
    examples:
      new-record-created:
        description: |
          Returns the Last created ID
        value:
          {
              "id": "5fbd30b2b74d924b796725ea",
              "statusCode": 201,
              "message": "Element created"
          }
