
body:
  application/json:
    example:
      {
          "statusCode": 200,
          "data": {
              "message": "A message with instructions was sent to the email account if it exists"
          }
      }
