
body:
  application/json:
    example:
      {
          "statusCode": 200,
          "data": {
              "id": "5fc115e9b50ae71dc946e3cb",
              "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1lMkBkYXJvbndvbGZmLmNvbSIsImZpcnN0TmFtZSI6IkpvZSIsImxhc3ROYW1lIjoiRG9lIiwiaWF0IjoxNjA2NDk1MjQ3LCJleHAiOjE2MDY0OTU2MDd9.BKZfbkxqcpzWFKl0goAAkqgdxZ4axlu6mdrZf4sZ9-o"
          }
      }
