body:
  application/json:
    examples:
      not-found:
        description: 'A resource was not found'
        value:
          {
              "statusCode": 404,
              "message": "Not Found",
              "errorDetails": []
          }
