application/json:
  examples:
    login-user-information-required:
      description: Minimum payload required
      value:
        {
          "email": "demo@demo.com",
          "password": "passw0rd"
        }
