application/json:
  examples:
    reset-password:
      description: Payload required to update the password account
      value:
        {
            "password": "n3wS()p3rC0mplexP@ssw0rd",
            "verifyPassword": "n3wS()p3rC0mplexP@ssw0rd",
            "token": "7595766ad271cee18b6aee84efaa9a6e323eaf17"
        }
