body:
  application/json:
    examples:
      record-updated:
        description: |
          Returns confirmation that the element was updated
        value:
          {
              "statusCode": 200,
              "data": {
                  "message": "Element updated"
              }
          }