#%RAML 1.0
title: API Contract for Mhealth application
version: 1
protocols: HTTPS
mediaType: application/json

description: |
  Mhealt API RESTful interfaces

/profile:
  description: "Endpoints for View and Update User profile"
  get:
    description: "Endpoint to get Information about the User profile"
    responses:
      200: !include ./apis/users/responses/view-profile.raml
      403: !include ./shared/codes/403.raml
      500: !include ./shared/codes/500-internal-error.raml

  put:
    description: "Endpoint to update Information about the User profile"
    body: !include ./apis/users/bodies/update.raml
    responses:
      200: !include ./shared/responses/updated.raml
      403: !include ./shared/codes/403.raml
      500: !include ./shared/codes/500-internal-error.raml


################################################# Auth api ################################################
/auth:
  description: "Endpoint for authentication"
  /register:
    post:
      description: "To create new user accounts"
      body: !include ./apis/auth/bodies/register.raml
      responses:
        201: !include ./apis/auth/responses/created.raml
        400: !include ./apis/auth/codes/400.raml
        401: !include ./apis/auth/codes/401.raml
        409: !include ./apis/auth/codes/409-email-exists.raml
        500: !include ./shared/codes/500-internal-error.raml

  /activate-account:
    post:
      description: "Endpoint for user account activation"
      body: !include ./apis/auth/bodies/activate-account.raml
      responses:
        200: !include ./apis/auth/responses/activate-account.raml
        400: !include ./apis/auth/codes/400-activation-code.raml
        500: !include ./shared/codes/500-internal-error.raml

  /login:
    post:
      description: "Login for users"
      body: !include ./apis/auth/bodies/login.raml
      responses:
        200: !include ./apis/auth/responses/login.raml
        400: !include ./apis/auth/codes/400.raml
        401: !include ./apis/auth/codes/401.raml
        500: !include ./shared/codes/500-internal-error.raml

  /forgot-password:
    post:
      description: "Start recovery password process. User send email address, system sends en recovery password email"
      body: !include ./apis/auth/bodies/forgot-password.raml
      responses:
        200: !include ./apis/auth/responses/forgot-password.raml
        400: !include ./apis/auth/codes/400-forgot-pasword.raml
        500: !include ./shared/codes/500-internal-error.raml

  /reset-password:
    get:
      queryParameters:
        token:
          type: string
          description: token generated by forgot-password endpoint
          required: true
          example: token=0b60f3e32c4944e779426ee062fb92986d493c60
      description: "Display HTML to change password"
      responses:
        200:
          description: "Returns form in HTML to change password"
        500: !include ./shared/codes/500-internal-error.raml

    post:
      description: "Validates the token and resets the password"
      body: !include ./apis/auth/bodies/reset-password.raml
      responses:
        200: !include ./apis/auth/responses/reset-password.raml
        400: !include ./apis/auth/codes/400-reset-password.raml
        500: !include ./shared/codes/500-internal-error.raml
